# This is a basic workflow to help you get started with Actions

name: Daily Submit

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
   schedule:
    - cron: '1 0,23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  submit:
    runs-on: ubuntu-latest
    # 定义系统类型，这里选择Ubuntu
    steps:
    - name: '[Prepare] Code Check'
      uses: actions/checkout@v2
      # 从该仓库clone代码到虚拟机
    - name: '[Prepare] Set python'
      uses: actions/setup-python@v1
      # 安装python
      with:
        python-version: '3.x'
    - name: '[Prepare] Install Dependencies'
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade lxml
        python -m pip install --upgrade requests
        # 安装需要的python库
    - name: '[Final Main] Working'
      env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }} 
      run: |
        python main.py
        # 执行代码
